### ISSUE TITLE
用自己的公众号推送失败，但是用测试公众号推送成功

### ISSUE THREAD

**Issue by chenxitianyao** [wangxinleo/wechat-public-account-push#10]
多谢分享，能不能出一个真正的公众号的使用教程，谢谢。目前使用测试的公众号，手动推送成功，但是换成自己的公众号就出错，说是ip不在白名单内，将该ip加入白名单后，还是出现同样的错误，只是ip就变成其他ip了，显示错误40001，具体如下：
请求失败 invalid ip 20.245.21.198 ipv6 ::ffff:20.245.219.198, not in whitelist rid: 630a08c9-7ecfb68b-06f36e1c
推送失败！ 
 errcode: 40001,
 errmsg: 'invalid credential, access_token is invalid or not latest rid: 630a08cb-79f5bf51-02b59fc7'

**Comment by wangxinleo** [comment]
噢，目前我还没有接入真正的公众号，还是个小玩具，你可以在根目录的main.js更改成真正公众号的推送链接来进行推送。

主要还是我的公众号目前还在注销期，我还没办法做测试，所以一直没有接入。

实在等不及可以自己改改看，不行就等我下次更新这个小玩具了哈哈。
