### ISSUE TITLE
关于目前仅支持测试号的问题

### ISSUE THREAD

**Issue by wangxinleo** [wangxinleo/wechat-public-account-push#11]
目前这个小玩具仅支持测试号。微信公众号和企业号因为推送接口不一样，暂不支持直接更改配置使用，必须同步修改main.js的脚本才行。

因为只有 **服务号** 有 **模板消息** 推送功能， 订阅号没有！！！！

**服务号** 需要 **企业** 才能申请~ 

有相应需求的用户可能需要等我适配更多的接口或者踊跃贡献代码我们一起适配啦！

**Comment by chenxitianyao** [comment]
好的，谢谢，不过我没学过不会修改。等你的好消息，再次感谢！

**Comment by LordonCN** [comment]
刚注册了一个个人公众号，想要接口权限是不是得认证。。可是个人已经不给认证了。。 先拿测试的用着吧

**Comment by wangxinleo** [comment]
是的，个人公众号的权限可能需要很长的时间审批，下次我会适配另一种方式，微信测试号的标题确实太难看啦哈哈！😃
