### ISSUE TITLE
生日推送有个错误

### ISSUE THREAD

**Issue by Ghs0my** [wangxinleo/wechat-public-account-push#12]
<img width="867" alt="image" src="https://user-images.githubusercontent.com/85071313/187032547-e4e54d3c-19b5-4d42-98df-f7d9fd4f93c8.png">
nextBir是负数 不会大于0 不会走else
改了一下
<img width="912" alt="image" src="https://user-images.githubusercontent.com/85071313/187032633-bb3524c2-71fb-4636-be80-f3a575d25129.png">

**Comment by wangxinleo** [comment]
本来就是想着已经过了的生日不需要提醒了哈哈😂😂

**Comment by Ghs0my** [comment]
> 本来就是想着已经过了生日的不需要提醒了哈哈😂😂

卧槽 好像是这样哈😂😂

**Comment by LordonCN** [comment]
卧槽 刚在测试还在想怎么一直是null 原来是这样

**Comment by LordonCN** [comment]
> 本来就是想着已经过了的生日不需要提醒了哈哈😂😂

可以改成在今年提醒明年生日还有多少天

**Comment by wangxinleo** [comment]
哈哈，好的，我想想再改一版，因为是半天做出来的小玩具。😂😂😂😂null会直接推送过去吗？

**Comment by LordonCN** [comment]
> 哈哈，好的，我想想再改一版，因为是半天做出来的小玩具。😂😂😂😂null会直接推送过去吗？

null不会推送，我是看的流水线里面日志，加了点调试信息
