### ISSUE TITLE
推送时间不准确

### ISSUE THREAD

**Issue by Drew-qu** [wangxinleo/wechat-public-account-push#183]
![image](https://user-images.githubusercontent.com/102668166/190887637-768b4cd1-e499-46e0-9cd4-c7a4de0fa6e7.png)
有大佬知道怎么设置时间, 看看我这样设置对吗?
我想每天早上7:30推送

**Comment by wangxinleo** [comment]
建议你设置成 50 22 * * * 因为有延迟的原因。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年9月18日 13:44
收件人: ***@***.***>
抄送: ***@***.***>
主题: [wangxinleo/wechat-public-account-push] 推送时间不准确 (Issue #183)


[image]<https://user-images.githubusercontent.com/102668166/190887637-768b4cd1-e499-46e0-9cd4-c7a4de0fa6e7.png>
有大佬知道怎么设置时间, 看看我这样设置对吗?
我想每天早上7:30推送

―

**Comment by Drew-qu** [comment]
谢谢大佬, 我昨天按照你给的时间设置了, 结果也是中午12点多才推送的, 是不是延迟造成的?

**Comment by wangxinleo** [comment]
不可能吧，你今天设成30 22 * * * 看看，你确认改了吗？延迟不可能一样吧

**Comment by wangxinleo** [comment]
小伙伴，如果实在不行，可以联系我，我有时间帮你远程看看。我觉得不应该有这么高的延迟，我仍然认为是不是你没有保存更改

**Comment by Drew-qu** [comment]
我这应该是保存好的, 我把代码clone下来, 用vscode打开, 配置好之后, 提交本地库, 然后推到我的远程仓库里面去的, 应该没啥问题的
这是我的仓库地址(https://github.com/Drew-qu/wechat-public-account-push), 麻烦有时间帮我看看, 谢谢大佬

**Comment by wangxinleo** [comment]
我看你已经自动推送成功了。这个文件设置成 30 22 * * * 才能符合你大概7点左右收到的要求。
***@***.***

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年9月20日 17:24
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [wangxinleo/wechat-public-account-push] 推送时间不准确 (Issue #183)


我这应该是保存好的, 我把代码clone下来, 用vscode打开, 配置好之后, 提交本地库, 然后推到我的远程仓库里面去的, 应该没啥问题的
这是我的仓库地址(https://github.com/Drew-qu/wechat-public-account-push), 麻烦有时间帮我看看, 谢谢大佬

―

**Comment by wangxinleo** [comment]
![image](https://user-images.githubusercontent.com/28293988/191267145-bf21fce8-baa7-4587-807d-efeb7dcb709a.png)
