### ISSUE TITLE
正式的微信订阅号操作步骤和这个一样嘛> 如何修改公众号名字

### ISSUE THREAD

**Issue by 99Awen** [wangxinleo/wechat-public-account-push#2]
> 如何修改公众号名字

测试的公众号不能修改名字，需要申请正式的微信订阅号

_Originally posted by @wangxinleo in https://github.com/wangxinleo/wechat-public-account-push/issues/1#issuecomment-1228608011_

**Comment by wangxinleo** [comment]
并不一样。会复杂一点点。

但是我相信你在百度中搜索【微信开放平台】，点击注册，一步一步下来，进去你自己的公众号管理平台之后，就能找到类似的本脚本需要的东西了。

百度也可以解决很多你找不到的东西，搜索就好了。

有机会我会补充正式的微信公众号的说明的😃

**Comment by 99Awen** [comment]
好的，谢谢啦
