### ISSUE TITLE
对于不同地区用户的天气应该如何配置

### ISSUE THREAD

**Issue by zhucexy** [wangxinleo/wechat-public-account-push#282]
请教一下多用户不同地区的天气信息，使用天行天气在Secrets里的配置应该如何填写？

**Comment by wangxinleo** [comment]
config.cjs中有个user数组，在里面可以添加多个user对象，里面的user对象也可以设置单独的地区来获取不同的天气。

具体参考3.confg的配置说明。

如果还不理解，可以拉到文档最下，

有个加群答疑，

这样及时性高一些。🥰

**Comment by zhucexy** [comment]
我在settings——secrets——actions里添加了user_info，并配置多个用户不同地区，测试推送结果每个用户正常显示对应的地区，但是天气信息都以users数组前面第一个的数值呈现，并没有显示对应地区的天气

**Comment by zhucexy** [comment]
另，你说的config.cjs是在哪个文件夹内呢，我想尽量不直接在原文件上记录

**Comment by wangxinleo** [comment]
1. user_info 只要能正常显示地区，就可以显示正常的对应天气。
2. 除非天气信息空白，那就是没获取到对应的地区代码，可以尝试只填城市而不填省份尝试一下。
3. config.cjs 是第二步方式2的方法。因为方式一的开发者两个月没更新了，所以可能已经不太适配我得配置文件，所以我建议您试试看用方式2的形式修改配置。

**Comment by zhucexy** [comment]
只是希望不用明文暴露在配置文件中

**Comment by wangxinleo** [comment]
噢~你可以使用导入的方式使用本项目，然后设为私有即可~因为参数实在太多了，对于secret方面的转化还得需要时间适配。

**Comment by zhucexy** [comment]
好吧！感谢耐心回复

**Comment by zhucexy** [comment]
重新私有部署并修改了配置，似乎依然是只能获取一个地方的天气信息，举个例子：A是广东深圳，B是广西桂林，A和B都只会显示A的城市天气，即使去掉省份也一样情况

**Comment by wangxinleo** [comment]
![image](https://user-images.githubusercontent.com/28293988/199131285-3cc2deaa-4679-46cd-965d-e2881e8166e4.png)
![image](https://user-images.githubusercontent.com/28293988/199131305-4077cf7f-ea1c-43c9-a624-4f253cdb3e7f.png)
![image](https://user-images.githubusercontent.com/28293988/199131313-f91cb43f-a20d-4559-a667-60ff9e3e98cd.png)
