### ISSUE TITLE
模板消息如何配置

### ISSUE THREAD

**Issue by mumudd** [wangxinleo/wechat-public-account-push#307]
微信公众平台想要配置模板消息得是企业号才行吧,如果不是想要配置模板消息只能使用测试号是吗

**Comment by wangxinleo** [comment]
正式的微信公众号平台需要认证的企业服务号，而且模板消息需要审核（我们这种私人内容基本上审核不通过），所以个人使用还是建议使用测试号，如果想要推送的内容可以像联系人一样置顶，就使用教程中提供的第三方服务号进行相应配置。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年12月29日 11:20
收件人: ***@***.***>
抄送: ***@***.***>
主题: [wangxinleo/wechat-public-account-push] 模板消息如何配置 (Issue #307)


微信公众平台想要配置模板消息得是企业号才行吧,如果不是想要配置模板消息只能使用测试号是吗

―
