### ISSUE TITLE
最高最低气温一样，测试的山西陕西都是这样

### ISSUE THREAD

**Issue by yinghedx** [wangxinleo/wechat-public-account-push#31]
![38d8cb42e1c139cc65a95fbf2a08204](https://user-images.githubusercontent.com/112332787/187081585-2b83772b-2862-4070-a857-6259f366d3e5.jpg)

**Comment by wangxinleo** [comment]
我查了一下这两个城市，确实28号的温差特别小。。😂😂这个温度很难保证所有软件全国统一。
