### ISSUE TITLE
为啥老提示这个啊

### ISSUE THREAD

**Issue by 1601085394** [wangxinleo/wechat-public-account-push#34]
推送失败!{
错误代码:40003，
errmsg:“无效的OpenID rid:630 b9f 21-7 ab 17 fad-4372 cc73”

**Comment by wangxinleo** [comment]
你这个id，怎么中间会有那么多空格，请问你使用的是测试号吗？请截图一下你的配置信息图。

**Comment by qilaile** [comment]
大佬，这个怎么解决呀
推送失败！ {
  errcode: 40003,
  errmsg: 'invalid openid rid: 630c564c-0ddb59e1-5f81042f'
}

**Comment by wangxinleo** [comment]
被你问的我都有点蒙了，会不会你参数填错了呢？都对应上了吗？是测试号吗？
