### ISSUE TITLE
服务器上定时推送报错

### ISSUE THREAD

**Issue by yxplus1116** [wangxinleo/wechat-public-account-push#347]
本地手动推送正常，服务器上定时推送报错，是何原因？如图：
<img width="1072" alt="image" src="https://github.com/wangxinleo/wechat-public-account-push/assets/40259902/d6ea694d-870b-4b1d-a42b-d4a977a67268">

**Comment by wangxinleo** [comment]
感谢，已经重新部署证书啦！谢谢你

> 本地手动推送正常，服务器上定时推送报错，是何原因？如图： <img alt="image" width="1072" src="https://user-images.githubusercontent.com/40259902/253736140-d6ea694d-870b-4b1d-a42b-d4a977a67268.png">
