### ISSUE TITLE
消息发送失败

### ISSUE THREAD

**Issue by xiaozhenlei** [wangxinleo/wechat-public-account-push#361]
![image](https://github.com/wangxinleo/wechat-public-account-push/assets/93065862/855a0589-d8b9-4835-ad51-c059672475f3)
如图所示

**Comment by wangxinleo** [comment]
进入文件夹查看一下更详细的报错信息

**Comment by SakuraCodes** [comment]
![image](https://github.com/wangxinleo/wechat-public-account-push/assets/30657641/6100a9be-a415-47b1-8987-84a07ada2afb)

![image](https://github.com/wangxinleo/wechat-public-account-push/assets/30657641/6163c925-9023-472a-bdd0-dbd4731b8e12)
如图所示，不太清楚如何更新node.js，大佬求解

**Comment by SakuraCodes** [comment]
> 进入文件夹查看一下更详细的报错信息

https://private-user-images.githubusercontent.com/30657641/321117163-6100a9be-a415-47b1-8987-84a07ada2afb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3Mjg2NzksIm5iZiI6MTcxMjcyODM3OSwicGF0aCI6Ii8zMDY1NzY0MS8zMjExMTcxNjMtNjEwMGE5YmUtYTQxNS00N2IxLTg5ODctODRhMDdhZGEyYWZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDA1NTI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiZTNkNmNjYjQ3NGM3NGNiY2YyMTQ3NDVkOTc1OWE4ZWM1MWQ5NGMwNjUyNDA0OTZlMDAxNTg5NjQ5YTI1ZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t99cY0ZL-bOg5QhMkxL-rqTb-6RSJnmNQ7SKCiQ7-P0

**Comment by SakuraCodes** [comment]
> 进入文件夹查看一下更详细的报错信息

![image](https://github.com/wangxinleo/wechat-public-account-push/assets/30657641/f2eced63-0a6c-4445-be1a-c4542dcc1f84)
