### ISSUE TITLE
您好，请问可以把微信测试公众号换成微信公众号通知吗？

### ISSUE THREAD

**Issue by Auto-Tifou** [wangxinleo/wechat-public-account-push#369]
您好，请问可以把微信测试公众号换成微信公众号通知吗？微信测试公众号有诸多不便，比如通知不明显，修改不了公众号名称等功能。所以我申请了一个微信公众号，能怎么把微信测试公众号换成公众号进行操作吗？我在微信公众号平台没看到有模板和扫码绑定等功能？多谢

**Comment by anthonywjq2018** [comment]
很遗憾的说，目前这个小玩具仅支持测试号。

微信公众号和企业号因为推送接口不一样，暂不支持直接更改配置使用。

因为只有 服务号 有 模板消息 推送功能， 订阅号没有！！！！

服务号 需要 企业 才能申请~

有相应需求的用户可能需要等我适配更多的接口或者踊跃贡献代码我们一起适配啦！
From https://github.com/wangxinleo/wechat-public-account-push/discussions/23

**Comment by Auto-Tifou** [comment]
> 很遗憾的说，目前这个小玩具只支持测试号。
> 
> 微信公众号和企业号因为大众接口不一样，暂时不支持直接更改配置使用。
> 
> 因为只有服务号有模板消息自主功能，订阅号没有！
> 
> 服务号 需要企业人才申请~
> 
> 有相应需求的用户可能需要等我装备更多的接口或者踊跃贡献代码我们一起装备啦！ 来自#23

好的 谢谢！期待！
