### ISSUE TITLE
40003错误

### ISSUE THREAD

**Issue by qilaile** [wangxinleo/wechat-public-account-push#37]
大佬，这个错误怎么解决呢？
推送失败！ {
  errcode: 40003,
  errmsg: 'invalid openid rid: 630c564c-0ddb59e1-5f81042f'
}

**Comment by wangxinleo** [comment]
1. 确认自己的号是不是测试号，目前只有服务号才有推送功能，服务号只能企业申请
2. 以下参数对应上了吗？

![1661756547(1)](https://user-images.githubusercontent.com/28293988/187142684-683277a6-5ce9-4d0e-aad4-428e4633cc53.jpg)

![image](https://user-images.githubusercontent.com/28293988/187142816-2f0f6dc0-20ae-48b0-8991-aa3143fbd44f.png)

![image](https://user-images.githubusercontent.com/28293988/187142960-da217045-3859-4179-a40c-e15baeea27c4.png)

**Comment by qilaile** [comment]
那测试号不能推送吗？我是测试号

**Comment by wangxinleo** [comment]
@qilaile 测试号可以推送，我刚刚自己又测了一下最新代码仓库的代码。确认不是代码bug，是能成功发送的。 如果你还解决不了，可以给我发送邮件，wangxin.leo@outlook.com ，把你的敏感配置都发邮件给我，我进行单独测试。

**Comment by qilaile** [comment]
发给您了

**Comment by wangxinleo** [comment]
@qilaile 你的 月亮** 那个微信号应该已经收到推送了吧

我用你提供的参数是没有问题的，已经成功发送。

注意看我的邮件回复，好好检查一下自己的配置是否正确。

![image](https://user-images.githubusercontent.com/28293988/187148033-7d2fc7a9-6d96-4d0b-b98b-fc0040c1c4eb.png)
