### ISSUE TITLE
关于定时任务好像（？）没有自动执行

### ISSUE THREAD

**Issue by wangxinleo** [wangxinleo/wechat-public-account-push#4]
目前github action并不可靠，因为它是整个github所有的脚本共同排队执行的，触发时间并不准时。（有些人也许只是晚5分钟，有些人也许是1小时，还有些人可能是一天😂😂）

如果需要可靠的定时任务需要寻找其他途径。

我在尝试把本项目clone一份在gitee上尝试gitee提供的工作流方案。😃

**Comment by LordonCN** [comment]
`- cron: '0 3 1 5 *'`
我期望上午11:15 运行的话是这样配置吗？ 刚测试了一下确实发现没有触发，当然也不清楚配置的对不对

**Comment by wangxinleo** [comment]
😂😂你这个配的离大谱。

你可以先设置 30 * * * *  测试一下每半个小时的延迟大概是多少。


成功了之后， 

15 3 * * *  才是你想要的11:15分的推送

**Comment by wangxinleo** [comment]
具体在https://docs.github.com/cn/actions/using-workflows/events-that-trigger-workflows

自行查看 cron规则。

**Comment by LordonCN** [comment]
> 具体在https://docs.github.com/cn/actions/using-workflows/events-that-trigger-workflows
> 
> 自行查看 cron规则。

可以可以 理解了
