### ISSUE TITLE
怎么更改自动执行的时区

### ISSUE THREAD

**Issue by worldno1** [wangxinleo/wechat-public-account-push#49]
就比如说我现在想要在北京时间上午6点自动执行，那个cron设置的时间就是国际时间昨天的22点，今天早上6点多自动执行之后，上面的时间还是昨天，那这个要怎么解决呢

**Comment by wangxinleo** [comment]
啊，是个好问题，我好像没考虑到这个，我要测试一下。

**Comment by chenxitianyao** [comment]
之前设置是国际时间0 0，对应北京时间8点，推送会推迟到10点左右；现在改成了 2 2，对应早上6点，结果推迟的更晚了都到了12点了，但日期还是对的。

**Comment by wangxinleo** [comment]
2 2 * * * 对应的应该是10点02分吧哈哈哈哈。然后推迟一下给你推到12点了。。🥺🥺

要不测一测0 22 * * * 看看是什么效果？

**Comment by worldno1** [comment]
诶，日期还是对的？！！就离谱，我一大早起来就看到今天推送的时间不对，内容和昨天的一模一样，我就在想是不是国际时间还是昨天的原因



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月30日(周二) 晚上9:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wangxinleo/wechat-public-account-push] 怎么更改自动执行的时区 (Issue #49)




 
之前设置是国际时间0 0，对应北京时间8点，推送会推迟到10点左右；现在改成了 2 2，对应早上6点，结果推迟的更晚了都到了12点了，但日期还是对的。

**Comment by wangxinleo** [comment]
我今天晚上测试一下看看。我调到了utc 22点执行会是什么效果。想要白嫖人家搞无无服务器版确实好多东西要考虑呀。

**Comment by wangxinleo** [comment]
啊哈哈哈哈，听到你那么支持我超开心的！！

我今天挤破脑袋都在想怎么把这这个action的问题解决掉，让它可能做到无延迟。

你说的话给了我超大鼓舞！！🌈🌈

**Comment by worldno1** [comment]
啊哈哈哈哈！！！带我暴富！！！迎娶白富美，走上人生巅峰！怎么办！我真的好激动，像极了见偶像！！啊哈哈哈哈！我的天！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月30日(周二) 晚上11:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wangxinleo/wechat-public-account-push] 怎么更改自动执行的时区 (Issue #49)




 
阿这这这！！  怎么办！我好害羞啊~~~我一定要把你牢牢抓到我的心里❤️！！
 
快告诉我，我怎么样才能得到你哈哈~~🌝

**Comment by wangxinleo** [comment]
测出来了，确实跟你说的情况一样。utc 22:00还是会推送前一天的数据。😼😼，我今天修复一下。

**Comment by worldno1** [comment]
0 22 * * *我还真有运行 上一封邮件的附件里就有



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月30日(周二) 晚上9:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wangxinleo/wechat-public-account-push] 怎么更改自动执行的时区 (Issue #49)




 
2 2 * * * 对应的应该是10点02分吧哈哈哈哈。然后推迟一下给你推到12点了。。🥺🥺
 
要不测一测0 22 * * * 看看是什么效果？
