### ISSUE TITLE
自动推送问题

### ISSUE THREAD

**Issue by youareaperson** [wangxinleo/wechat-public-account-push#50]
我这个为什么不能自动推送~不太懂

**Comment by tslace** [comment]
我也是，昨晚手动跑过没问题。
截止到现在还没收到。

**Comment by wangxinleo** [comment]
请看讨论组中关于《好像自动运行没触发》的回答

**Comment by wangxinleo** [comment]
你们可以尝试先设置30分钟每次看看能否成功，因为存在延时，特别是utc0点这种高拥堵时段

**Comment by youareaperson** [comment]
咋设置30分钟

**Comment by wangxinleo** [comment]
目前github action并不可靠，因为它是整个github所有的脚本共同排队执行的，触发时间并不准时。

（有些人也许只是晚5分钟，有些人也许是1小时，还有些人可能是一天😂😂）

你可以先设置 30 * * * * 测试一下每半个小时的延迟大概是多少。

如果需要可靠的定时任务需要服务器支撑。或者本地有设备能跑。晚点看看出教程吧。如果很需要的话。

**Comment by LordonCN** [comment]
> 目前github action并不可靠，因为它是整个github所有的脚本共同排队执行的，触发时间并不准时。
> 
> （有些人也许只是晚5分钟，有些人也许是1小时，还有些人可能是一天😂😂）
> 
> 你可以先设置 30 * * * * 测试一下每半个小时的延迟大概是多少。
> 
> 如果需要可靠的定时任务需要服务器支撑。或者本地有设备能跑。晚点看看出教程吧。如果很需要的话。

我这两天测试发现我action选的是我自己的开发分支，第二天到时间后默认跑的是未修改过的master分支

**Comment by wangxinleo** [comment]
> > 目前github action并不可靠，因为它是整个github所有的脚本共同排队执行的，触发时间并不准时。
> > （有些人也许只是晚5分钟，有些人也许是1小时，还有些人可能是一天😂😂）
> > 你可以先设置 30 * * * * 测试一下每半个小时的延迟大概是多少。
> > 如果需要可靠的定时任务需要服务器支撑。或者本地有设备能跑。晚点看看出教程吧。如果很需要的话。
> 
> 我这两天测试发现我action选的是我自己的开发分支，第二天到时间后默认跑的是未修改过的master分支

因为脚本默认 checkout master ，如果要checkout你自己的分支的话，就需要加命令。

**Comment by xiaoBunny** [comment]
《好像自动运行没触发》这个在哪看

**Comment by wangxinleo** [comment]
> 《好像自动运行没触发》这个在哪看
> 

可能你没有启用actions，文档教程仔细跟一遍，实在不懂就加群细说吧，我也不知道你卡在哪一步😂😂

**Comment by xiaoBunny** [comment]
麻烦发一下群号吧，我加一下群






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangxinleo/wechat-public-account-push"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月3日(星期六) 中午11:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangxinleo/wechat-public-account-push] 自动推送问题 (Issue #50)





  
《好像自动运行没触发》这个在哪看
  
可能你没有启用actions，文档教程仔细跟一遍，实在不懂就加群细说吧，我也不知道你卡在哪一步😂😂

**Comment by wangxinleo** [comment]
阿这。。。。文档里有。。。群。。。和二维码。。。。看不到图片也有国内镜像链接可以看到。。
