### ISSUE TITLE
(求大佬)🏥怎么样才能让小白不用下源码，不用装环境，不需要了解docker，就能使用win或者linux的定时任务呢？

### ISSUE THREAD

**Issue by wangxinleo** [wangxinleo/wechat-public-account-push#59]
求方案🚑🚑🚑🚑

(github actions 已经不具备让我们成为时间管理大师的能力了🤡🤡🤡)

(它的延时很容易让女朋友们感受不到我们的诚心😷😷😷)

(13:14 总不能变成15:23吧💩)

**Comment by q1263868407** [comment]
手动action

**Comment by q1263868407** [comment]
网上有腾讯云函数定时action（模拟手动）的教程

**Comment by wangxinleo** [comment]
> 网上有腾讯云函数定时action（模拟手动）的教程

那个现在收费了。😂😂😂现在腾讯云是服务器刺客。我上个月看到他的收费提醒，立马取消了我bili的脚本。

**Comment by FlawlessChen** [comment]
你用github的action就可以定时发送了，用不到win的定时任务

**Comment by condorheroblog** [comment]
这篇文章 [GitHub Actions workflow not triggering at scheduled time
](https://upptime.js.org/blog/2021/01/22/github-actions-schedule-not-working/) 讨论了自动任务延迟的问题，最后给了给了解决方案，见 [Is Uptime CI running every 5 minutes? ](https://github.com/upptime/upptime/issues/42#issuecomment-840264035) ，除非自建服务不然也会延迟。

而且就算是自建服务，推送也得经过腾讯的服务器，依然会有延迟。

**Comment by wangxinleo** [comment]
> 这篇文章 [GitHub Actions workflow not triggering at scheduled time
> ](https://upptime.js.org/blog/2021/01/22/github-actions-schedule-not-working/) 讨论了自动任务延迟的问题，最后给了给了解决方案，见 [Is Uptime CI running every 5 minutes? ](https://github.com/upptime/upptime/issues/42#issuecomment-840264035) ，除非自建服务不然也会延迟。
> 
> 而且就算是自建服务，推送也得经过腾讯的服务器，依然会有延迟。

棒棒，我还去看了你的作品，看的出来你超有水平👍👍👍
