### ISSUE TITLE
推送模板问题

### ISSUE THREAD

**Issue by chenxitianyao** [wangxinleo/wechat-public-account-push#61]
同样的模板，前面的就可以，后面的模板进行了断行，然后日期、城市、天气信息就没有显示，也没有报错。不知道是哪里的问题。
![template](https://user-images.githubusercontent.com/34850260/187473578-38d60e47-c85c-4c02-973d-10e6ca8cc47b.jpg)

**Comment by wangxinleo** [comment]
重新完整复制readme中提供的模板后再手动推送看看能不能解决你的问题。

如果自己定制，最好在 代码编辑器 或者 记事本 中，做好格式，再到测试号中配置。 全程复制粘贴，最好不要在测试号中手动改。他那里可能会覆盖掉你本身应有的格式。

**Comment by chenxitianyao** [comment]
找到问题了，浏览器开了自动拼写更正的插件，导致 date.DATA 变成了date. DATA，DATA前多了一个空格，去掉空格即可。

**Comment by chenxitianyao** [comment]
感谢！
