### ISSUE TITLE
invalid credential, access_token is invalid or not latest rid: 630ecbee-28894bea-0ee8d49c'

### ISSUE THREAD

**Issue by liqiangnd** [wangxinleo/wechat-public-account-push#66]
请问下这个是什么问题呀？
<img width="858" alt="image" src="https://user-images.githubusercontent.com/87466009/187581970-092be578-aee9-4186-a17a-02ffbd4b6b34.png">

**Comment by wangxinleo** [comment]
**刚刚解决了几个朋友发邮件问我为什么会报错的问题，发现其实还是没看懂配置。**

0. 先fork最新的代码仓库。
1. 确认自己的号是不是测试号，目前只有服务号才有推送功能，服务号只能企业申请。
2. 以下参数对应上了吗？

![1661756547(1)](https://user-images.githubusercontent.com/28293988/187142684-683277a6-5ce9-4d0e-aad4-428e4633cc53.jpg)

![image](https://user-images.githubusercontent.com/28293988/187142816-2f0f6dc0-20ae-48b0-8991-aa3143fbd44f.png)

![image](https://user-images.githubusercontent.com/28293988/187142960-da217045-3859-4179-a40c-e15baeea27c4.png)

**Comment by lmq352489099** [comment]
CALLBACK_TEMPLATE_ID  也是直接填模板id吗

**Comment by lmq352489099** [comment]
我也是报了这个错误  ACCESS_TOKEN 我们是不用填的吗
