### ISSUE TITLE
获取 accessToken: 请求失败 invalid appsecret rid: 630f0975-62a5440a-73a658c0

### ISSUE THREAD

**Issue by lmq352489099** [wangxinleo/wechat-public-account-push#67]
1.在配置完成之后,actions里面操作脚本
 2.获取 accessToken: 请求失败 invalid appsecret rid: 630f0975-62a5440a-73a658c0

**Comment by wangxinleo** [comment]
肯定是你东西没填对。。。你真的认真对照一下。。。

**Comment by lmq352489099** [comment]
谢谢,配置没错,是微信那边的问题,appsecret 重新生成就OK了.
请问下我想做某个时段发送消息, 比如 早上的 10点触发该消息 这个在哪里配置呀

**Comment by wangxinleo** [comment]
看一下文档。readme写得很详细了。

我在考虑还是拉个群方便给你们答疑吧哈哈😂😂😂

**Comment by lmq352489099** [comment]
文档是写的很棒,只是我github用的不是很好,可以拉个群的,我想大家都很喜欢这种方式

**Comment by chiqingsong** [comment]
重新生成了个appsecret确实ok了 感谢 也感谢leo

**Comment by 1670642712** [comment]
怎么重新生成个appsecret

**Comment by wangxinleo** [comment]
> 怎么重新生成个appsecret

刷新或重新登陆即可。主要是第一次登陆生成的可能是错的。❌

**Comment by 1670642712** [comment]
有没有群 我加一下

**Comment by wangxinleo** [comment]
> 有没有群 我加一下

😂啊，我还没考虑好。我如果建群了我会写在文档上的。

**Comment by LordonCN** [comment]
群在这里！
https://github.com/wangxinleo/wechat-public-account-push/blob/ebae32223b1120aec2214f7dd7f97a7345ef1287/README.md?plain=1#L181
