### ISSUE TITLE
当生日日期小于当前日期，无法生成倒计时

### ISSUE THREAD

**Issue by pyrrole-ach** [wangxinleo/wechat-public-account-push#7]

**Comment by wangxinleo** [comment]
生日仅填写月日即可，请严格按照例子填写吧

**Comment by twtcel1** [comment]
生日是明年的时候，不能正常显示？？？

**Comment by wangxinleo** [comment]
今年已经过去了的生日默认不展示，现实时间到了第二年就会展示了。

但是我想我会优化一下这个显示方案，未来几天我会将最近的两次重要生日进行展示

期待下次更新吧😃

**Comment by asd4451874** [comment]
生日我瞎改了一下，直接计算一下当前时间是否过了生日的时间然后过了加一年就好了
