### ISSUE TITLE
模板推送问题

### ISSUE THREAD

**Issue by yn22638** [wangxinleo/wechat-public-account-push#74]
请问这个 ios 端，他的日期可以取消显示吗
![image](https://user-images.githubusercontent.com/48940123/187855647-83efdc29-e352-4733-a3e2-24bb2a149392.png)

**Comment by wangxinleo** [comment]
哦吼！

我暂时没找到取消这类推送预置文本的方法🥺

**Comment by yn22638** [comment]
> 哦吼！
> 
> 我暂时没有找到搜索工具的方法🥺

欧克欧克，影响不大，安卓是不显示这个日期的，只有 ios 才会，我也在找解决办法

**Comment by yn22638** [comment]
> 哦吼！
> 
> 我暂时没有找到工具的方法🥺

欧克欧克，影响不大，安卓不显示日期的，只有ios会用这个，我也在找解决办法

**Comment by yn22638** [comment]
> 
okok，影响不大， anzhuo 不显示日期的，只有ios会显示这个，我页在找解决办法
