### ISSUE TITLE
推送失败

### ISSUE THREAD

**Issue by angping** [wangxinleo/wechat-public-account-push#8]
大哥，这个错误怎么解决，文档说是【AppSecret错误或者 AppSecret 不属于这个公众号，请开发者确认 AppSecret 的正确性】，不过好像没错
errcode: 40001,
  errmsg: 'invalid credential, access_token is invalid or not latest rid

**Comment by wangxinleo** [comment]
可不可以截图让我看看你的配置信息是怎么配置的。

**Comment by FenYuBin** [comment]
errcode: 40001,
  errmsg: 'invalid credential, access_token is invalid or not latest rid: 630a42cc-1f1e97c2-6af53c32'

**Comment by FenYuBin** [comment]
这样子是什么问题。。有人遇到了吗
